### ISSUE TITLE
Need help and advice

### ISSUE THREAD

**Issue by alifpay** [rodaine/grpc-chat#2]
Hi

I am developing go application. It has main application and plugins. 
I did current version with plugin from go package https://golang.org/pkg/plugin/
this package has problems that we decide to change it. 

I look into hashicorp/go-plugin, it is good but main application must connect to plugins, we want plugins must connect to main application like server clients, and server can send message to clients.

I decide to do like your chat application.

How to send message from server specifically related to this client? example client has id, server gets records from db and group by client id and send message to clients.

in TCP connection, when client connects to server, and server accepts connection, we keep connection in memory by client id. 

I do not understand how to do in grpc ?

**Comment by rodaine** [comment]
A good way to associate the client ID with the connection is to send it as part of the [outgoing metadata](https://godoc.org/google.golang.org/grpc/metadata#NewOutgoingContext) (which, effectively are just HTTP headers). Then, on the server side, you can read the `IncomingMetadata` off the context and associate the stream with that client.
