### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ashaw1131** [rodaine/grpc-chat#4]
Im using this internally in my business and I cannot get it to log conversations and users names with timestamps, any idea? My business is 3 people all working in the same house but all of us communicate via chat so we can stay busy. I'd love to be able to log everything.

**Comment by rodaine** [comment]
Hi! @ashaw1131, glad you're getting some use out of this project. The project was meant to demonstrate features of gRPC for a meetup talk, so it's not fully fleshed out as a complete chat solution.

If I understand your question correctly, the server doesn't log anything, but you want to have a full chat history. One way to do this is to connect a client, and have it propagate its stderr/out to a file:

```sh
touch /var/log/chat.txt
grpc-chat -h "chat.example.com:6262" -p "super-secret" -n "Logger" 2>&1 >> /var/log/chat.txt
```
